name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-ignore-it'
          if_key_exists: replace

      - name: Sync files to Beget
        run: |
          rsync -avz --omit-dir-times --no-perms \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git*' \
            --exclude '.github*' \
            ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/${{ secrets.TARGET }}/
